# DataLab setup configuration file

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cdlapp"
authors = [{ name = "Codra", email = "p.raybaut@codra.fr" }]
description = "DataLab (CDL) is a data processing and analysis software for scientific and industrial applications"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Human Machine Interfaces",
    "Topic :: Software Development :: User Interfaces",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: OS Independent",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.8, <4"
dependencies = [
    "h5py >= 3.0",
    "NumPy >= 1.21",
    "SciPy >= 1.7",
    "scikit-image >= 0.18",
    "opencv-python >= 4.5",
    "PyWavelets >= 1.1",
    "psutil >= 5.5",
    "guidata >= 3.2",
    "plotpy >= 2.0",
    "QtPy >= 1.9",
]
dynamic = ["version"]

[project.scripts]
cdlapp-alltests = "cdlapp.tests.all_tests:run"

[project.gui-scripts]
cdlapp = "cdlapp.app:run"
cdlapp-demo = "cdlapp.tests.demo:run"
cdlapp-tests = "cdlapp.tests:run"

[project.optional-dependencies]
dev = ["black", "isort", "pylint", "Coverage"]
doc = ["PyQt5", "sphinx", "sphinx_intl", "pydata-sphinx-theme"]

[tool.setuptools.packages.find]
include = ["cdlapp*"]

[tool.setuptools.package-data]
"*" = [
    "*.png",
    "*.svg",
    "*.mo",
    "*.txt",
    "*.json",
    "*.h5",
    "*.npy",
    "*.dcm",
    "*.scor-data",
    "*.tiff",
    "*.jpg",
    "*.sif",
    "*.csv",
    "*.js",
    "*.css",
    "*.html",
    "*.buildinfo",
    "*.inv",
]

[tool.setuptools.dynamic]
version = { attr = "cdlapp.__version__" }
